# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g newman newman-reporter-htmlextra
    - run: newman run TACIT.postman_collection.json -e Tacit.postman_environment.json -r htmlextra
    - run: pwd
    - run: ls
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
         # mail server settings
         server_address: smtp.gmail.com
         server_port: 465
         # user credentials
         username: ayodeji.adedeji@exquisappfactory.com
         password: qymwgyohbhzripgk
         # email subject
         subject: Tacit GraphQL API Test Suite Results - ${{ job.status }}
         # email body as text
         body: Please see the attached report.
         # comma-separated string, send email to
         to: ayodeji.adedeji@exquisappfactory.com
         # from email name
         from: Tacit GraphQL API Test
         attachments: ./newman/*.html
