# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install newman
    - run: npm install newman-reporter-htmlextra
    - run: newman run TACIT.postman_collection.json -e Tacit.postman_environment.json -r htmlextra
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
         # mail server settings
         server_address: smtp.gmail.com
         server_port: 465
         # user credentials
         username: ayodeji.adedeji@exquisappfactory.com
         password: qymwgyohbhzripgk
         # email subject
         subject: Tacit GraphQL API Test Suite Results - ${{ job.status }}
         # email body as text
         body:  AUTH>> ${{ toJson(steps.auth_service.outputs.auth) }} | PROFILE>> ${{ toJson(steps.profile_service.outputs.profile) }} | SKILLS >> ${{ toJson(steps.skill_service.outputs.skill) }}
         # comma-separated string, send email to
         to: ayodeji.adedeji@exquisappfactory.com
         # from email name
         from: Tacit GraphQL API Test
         attachments: ./newman/
